extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - prettier

plugins:
  - react
  - import
  - jsx-a11y
  - react-hooks

settings:
  react:
    version: detect

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  browser: true
  node: true

globals:
  React: false
  ReactDOM: false

rules:
  react/prop-types: off
  react/react-in-jsx-scope: off
